"use client";
import {useMemo,useState} from "react";import {CalendarDays,RefreshCw,Search,X} from "lucide-react";import {useRouter} from "next/navigation";import {PageHead,Status} from "@/components/admin/common";import {logAdminResponseFailure} from "@/components/admin/user-errors";
type Row={id:string;product:string;platform:string;status:string;scheduled:string;published:string;date:string;error:string};
export function PublishingClient({rows}:{rows:Row[]}){
 const router=useRouter();const[retrying,setRetrying]=useState(""),[retryError,setRetryError]=useState(""),[q,setQ]=useState(""),[platform,setPlatform]=useState("All platforms"),[status,setStatus]=useState("All statuses"),[date,setDate]=useState("");
 const shown=useMemo(()=>rows.filter(r=>r.product.toLowerCase().includes(q.toLowerCase())&&(platform==="All platforms"||r.platform===platform)&&(status==="All statuses"||r.status===status)&&(!date||r.date===date)),[rows,q,platform,status,date]);
 async function retry(id:string){setRetrying(id);setRetryError("");try{const response=await fetch(`/api/admin/publications/${id}/retry`,{method:"POST"});if(!response.ok){await logAdminResponseFailure(response,"retry publication");setRetryError(response.status===404?"This publishing record no longer exists. Refresh the page.":"The post could not be retried. Check the platform connection under Integrations and try again.");return}router.refresh()}catch(error){console.error("[Admin] retry publication request failed",error);setRetryError("The app could not connect to retry this post. Check your internet connection and try again.")}finally{setRetrying("")}}
 return <><PageHead title="Publishing center" description="Monitor every destination independently and resolve failures."/>{retryError&&<div role="alert" className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{retryError}</div>}<div className="mb-4 flex flex-wrap gap-3"><div className="flex min-w-64 flex-1 items-center gap-2 rounded-lg border bg-white px-3"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full py-2.5 text-sm outline-none" placeholder="Find a product…"/></div><select value={platform} onChange={e=>setPlatform(e.target.value)} className="input w-40"><option>All platforms</option><option>Website</option><option>Telegram</option><option>Instagram</option><option>Tiktok</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="input w-40"><option>All statuses</option><option>Failed</option><option>Published</option><option>Processing</option><option>Queued</option><option>Scheduled</option></select><label className="flex h-[42px] flex-none items-center gap-2 rounded-lg border bg-white px-3"><CalendarDays size={16}/><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="bg-transparent text-sm outline-none" aria-label="Filter publication date"/>{date&&<button type="button" onClick={()=>setDate("")} aria-label="Clear date filter"><X size={14}/></button>}</label></div>
 <div className="card table-wrap"><table><thead><tr><th>Product</th><th>Platform</th><th>Status</th><th>Scheduled</th><th>Published</th><th>Error</th><th>Actions</th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td className="font-semibold">{r.product}</td><td>{r.platform}</td><td><Status value={retrying===r.id?"Processing":r.status}/></td><td className="muted">{r.scheduled}</td><td className="muted">{r.published}</td><td className={r.error!=="—"?"text-red-600":"muted"}>{r.error}</td><td>{r.status==="Failed"?<button className="btn" disabled={retrying===r.id} onClick={()=>retry(r.id)}><RefreshCw size={14} className={retrying===r.id?"animate-spin":""}/>{retrying===r.id?"Retrying…":"Retry"}</button>:r.published!=="—"?<span className="muted text-sm">Complete</span>:"—"}</td></tr>)}</tbody></table>{shown.length===0&&<div className="p-8 text-center text-sm muted">No publications match these filters.</div>}</div></>}
