"use client";
import {zodResolver} from "@hookform/resolvers/zod";import {Controller,useFieldArray,useForm} from "react-hook-form";import {z} from "zod";import {CalendarDays,Camera,Check,CloudUpload,Globe2,MessageCircle,Plus,Save,Send,Trash2,Video} from "lucide-react";import {useEffect,useRef,useState} from "react";import {useRouter} from "next/navigation";import {CATALOG_CATEGORY_NAMES} from "@/lib/catalog-categories";import {productSchema} from "@/lib/validation/product";import {adminResponseMessage} from "@/components/admin/user-errors";import {ExistingMediaPreview,NewMediaPreview} from "./media-preview";
type Form=z.infer<typeof productSchema>;type Category={id:string;name:string;disabled?:boolean};type ExistingMedia={id:string;url:string;type:string;filename:string|null};
const platforms=[{id:"WEBSITE",name:"Website",icon:Globe2},{id:"TELEGRAM",name:"Telegram",icon:MessageCircle},{id:"INSTAGRAM",name:"Instagram",icon:Camera},{id:"TIKTOK",name:"TikTok",icon:Video}] as const;
const contents=[{platform:"TELEGRAM" as const,caption:"",hashtags:"",ctaText:"",ctaUrl:""},{platform:"INSTAGRAM" as const,caption:"",hashtags:"",ctaText:"",ctaUrl:""},{platform:"TIKTOK" as const,caption:"",hashtags:"",ctaText:"",ctaUrl:""}];
const catalogCategoryNames=new Set<string>(CATALOG_CATEGORY_NAMES);
class ProductFormError extends Error {}
export function ProductForm({id,initial,categories,existingMedia=[]}:{id?:string;initial?:Partial<Form>;categories:Category[];existingMedia?:ExistingMedia[]}){
 const router=useRouter(),fileInput=useRef<HTMLInputElement>(null),locked=useRef(false),savedProductId=useRef(id);const[files,setFiles]=useState<File[]>([]),[message,setMessage]=useState(""),[messageFailed,setMessageFailed]=useState(false),[schedule,setSchedule]=useState(false),[date,setDate]=useState(""),[time,setTime]=useState("");
 const categoryOptions=categories.filter(category=>catalogCategoryNames.has(category.name)||category.id===initial?.categoryId).map(category=>catalogCategoryNames.has(category.name)?category:{...category,name:`${category.name} (choose a new category)`,disabled:true});
 const defaults:Form={name:"",description:"",shortDescription:"",categoryId:categories[0]?.id??"",sku:"",price:0,currency:"ETB",stock:0,sizes:[],availability:"IN_STOCK",platforms:["WEBSITE"],platformContent:contents};
 const{register,control,watch,setValue,handleSubmit,formState:{errors,isSubmitting}}=useForm<Form>({resolver:zodResolver(productSchema),defaultValues:{...defaults,...initial,sizes:initial?.sizes??[],platformContent:initial?.platformContent??contents}});const selected=watch("platforms");
 const{fields:sizeFields,append:appendSize,remove:removeSize}=useFieldArray({control,name:"sizes"});const sizes=watch("sizes");const sizeStock=(sizes??[]).reduce((total,size)=>total+(Number(size.stock)||0),0);useEffect(()=>{if(sizeFields.length)setValue("stock",sizeStock,{shouldValidate:true})},[setValue,sizeFields.length,sizeStock]);
 function toggle(p:Form["platforms"][number]){setValue("platforms",selected.includes(p)?selected.filter(x=>x!==p):[...selected,p],{shouldValidate:true})}
 function lockActions(action:string,on:boolean){const form=fileInput.current?.form;if(!form)return;form.querySelectorAll("button").forEach(b=>b.disabled=on);[...form.querySelectorAll("button")].find(b=>b.textContent?.trim()===action)?.querySelector("svg")?.classList.toggle("animate-spin",on)}
 async function upload(productId:string){for(let i=0;i<files.length;i++){const data=new FormData();data.set("file",files[i]);data.set("productId",productId);data.set("isPrimary",String(existingMedia.length===0&&i===0));const response=await fetch("/api/admin/media",{method:"POST",body:data});if(!response.ok)throw new ProductFormError(await adminResponseMessage(response,`upload ${files[i].name}`,`The product was saved, but “${files[i].name}” could not be uploaded. Check the file and try again.`))}}
 async function persist(data:Form,action:"draft"|"publish"|"schedule"){if(locked.current)return;locked.current=true;const label=action==="draft"?"Save draft":action==="publish"?"Publish now":"Schedule";lockActions(label,true);setMessageFailed(false);setMessage(action==="draft"?"Saving product…":action==="publish"?"Starting publication…":"Scheduling publication…");try{const currentId=savedProductId.current;const response=await fetch(currentId?`/api/admin/products/${currentId}`:"/api/admin/products",{method:currentId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!response.ok)throw new ProductFormError(await adminResponseMessage(response,"save product","We couldn’t save this product. Check the highlighted details and try again."));const product=await response.json() as {id?:string};const productId=currentId??product.id;if(!productId)throw new ProductFormError("The product may have been saved, but its confirmation was incomplete. Return to the product list before trying again.");savedProductId.current=productId;await upload(productId);if(action!=="draft"){const endpoint=action==="publish"?"publish":"schedule";const body:Record<string,unknown>={platforms:data.platforms.map(x=>x.toLowerCase())};if(action==="schedule")body.scheduledAt=new Date(`${date}T${time}`).toISOString();const publication=await fetch(`/api/admin/products/${productId}/${endpoint}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!publication.ok)throw new ProductFormError(await adminResponseMessage(publication,`${action} product`,action==="publish"?"The product was saved, but publishing could not start. Check the selected platforms and try again.":"The product was saved, but it could not be scheduled. Check the date and time, then try again."))}router.push("/admin/products");router.refresh()}catch(error){console.error("[Admin] product form operation failed",error);locked.current=false;lockActions(label,false);setMessageFailed(true);setMessage(error instanceof ProductFormError?error.message:"The app could not connect. Check your internet connection and try again; your entries are still on this page.")}}
 return <form onSubmit={handleSubmit(d=>persist(d,"draft"))} className="pb-24"><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-5">
  <Section title="Product information"><div className="grid gap-4"><Field label="Product name" error={errors.name?.message}><input className="input" {...register("name")}/></Field><Field label="Description" error={errors.description?.message}><textarea rows={6} className="input" {...register("description")}/></Field><Field label="Short description"><textarea rows={2} className="input" {...register("shortDescription")}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Category"><select className="input" {...register("categoryId")}>{categoryOptions.map(c=><option key={c.id} value={c.id} disabled={c.disabled}>{c.name}</option>)}</select></Field><Field label="SKU"><input className="input" {...register("sku")}/></Field></div></div></Section>
  <Section title="Pricing & inventory"><div className="grid gap-4 sm:grid-cols-2"><Field label="Price" error={errors.price?.message}><div className="flex"><Controller control={control} name="currency" render={({field})=><select {...field} className="rounded-l-lg border px-3"><option>ETB</option><option>USD</option></select>}/><input type="number" step="0.01" className="input rounded-l-none" {...register("price")}/></div></Field><Field label={sizeFields.length?"Total stock":"Stock quantity"} error={errors.stock?.message}><input type="number" readOnly={sizeFields.length>0} className={`input ${sizeFields.length?"bg-[#f3f5f3]":""}`} {...register("stock")}/>{sizeFields.length>0&&<span className="muted mt-1 block text-xs">Calculated from the size quantities below.</span>}</Field><Field label="Availability"><select className="input" {...register("availability")}><option value="IN_STOCK">In stock</option><option value="OUT_OF_STOCK">Out of stock</option></select></Field><div className="sm:col-span-2"><label className="flex items-center gap-3 rounded-lg border p-3 text-sm font-semibold"><input type="checkbox" checked={sizeFields.length>0} onChange={event=>event.target.checked?appendSize({label:"",stock:0}):removeSize()}/>This product has sizes</label>{sizeFields.length>0&&<div className="mt-4 space-y-3"><div className="grid grid-cols-[minmax(0,1fr)_130px_40px] gap-2 px-1 text-xs font-semibold uppercase tracking-wide text-[#6f7a74]"><span>Size</span><span>Available</span><span/></div>{sizeFields.map((field,index)=><div key={field.id} className="grid grid-cols-[minmax(0,1fr)_130px_40px] gap-2"><div><input className="input uppercase" placeholder="S, M, L or 39" {...register(`sizes.${index}.label`)}/>{errors.sizes?.[index]?.label?.message&&<span className="mt-1 block text-xs text-red-600">{errors.sizes[index]?.label?.message}</span>}</div><div><input type="number" min="0" className="input" {...register(`sizes.${index}.stock`)}/>{errors.sizes?.[index]?.stock?.message&&<span className="mt-1 block text-xs text-red-600">{errors.sizes[index]?.stock?.message}</span>}</div><button type="button" className="btn px-0" aria-label={`Remove size ${index+1}`} onClick={()=>removeSize(index)}><Trash2 size={16}/></button></div>)}<button type="button" className="btn" onClick={()=>appendSize({label:"",stock:0})}><Plus size={16}/>Add another size</button></div>}</div></div></Section>
  <Section title="Product media"><input ref={fileInput} type="file" multiple accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" className="hidden" onChange={e=>{setFiles(v=>[...v,...Array.from(e.target.files??[])]);e.target.value=""}}/><button type="button" onClick={()=>fileInput.current?.click()} className="grid w-full place-items-center rounded-lg border border-dashed p-8"><CloudUpload/><span className="mt-2 font-semibold">Choose product images or video</span></button>{existingMedia.length+files.length>0&&<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{existingMedia.map(m=><ExistingMediaPreview key={m.id} media={m}/>)}{files.map((f,i)=><NewMediaPreview key={`${f.name}-${f.lastModified}-${i}`} file={f} onRemove={()=>setFiles(v=>v.filter((_,n)=>n!==i))}/>)}</div>}</Section>
  <Section title="Platform-specific content">{contents.map((c,i)=><div className="grid gap-3 border-b py-4" key={c.platform}><b>{c.platform[0]+c.platform.slice(1).toLowerCase()}</b><input type="hidden" {...register(`platformContent.${i}.platform`)}/><textarea className="input" placeholder="Custom caption" {...register(`platformContent.${i}.caption`)}/><input className="input" placeholder="Hashtags" {...register(`platformContent.${i}.hashtags`)}/>{c.platform==="TELEGRAM"&&<div className="grid gap-3 sm:grid-cols-2"><input className="input" placeholder="CTA text" {...register(`platformContent.${i}.ctaText`)}/><input className="input" placeholder="https://…" {...register(`platformContent.${i}.ctaUrl`)}/></div>}</div>)}</Section>
 </div><aside><Section title="Publish to"><div className="space-y-2">{platforms.map(p=>{const active=selected.includes(p.id),Icon=p.icon;return <button key={p.id} type="button" onClick={()=>p.id!=="WEBSITE"&&toggle(p.id)} className={`flex w-full items-center gap-3 rounded-lg border p-3 ${active?"border-[#71aa94] bg-[#f2f8f5]":""}`}><Icon size={17}/><span className="flex-1 text-left font-semibold">{p.name}</span>{active&&<Check size={16}/>}</button>})}</div></Section></aside></div>
 <div className="fixed inset-x-0 bottom-0 z-20 border-t bg-white p-3 lg:left-[238px]"><div className="mx-auto flex max-w-[1500px] items-center gap-2"><span role={messageFailed?"alert":"status"} className={`text-sm ${messageFailed?"text-red-600":"muted"}`}>{message}</span><div className="ml-auto flex gap-2"><button type="submit" disabled={isSubmitting} className="btn"><Save size={16}/>Save draft</button><button type="button" onClick={()=>setSchedule(true)} className="btn"><CalendarDays size={16}/>Schedule</button><button type="button" onClick={handleSubmit(d=>persist(d,"publish"))} className="btn btn-primary"><Send size={16}/>Publish now</button></div></div></div>
 {schedule&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4"><div className="card w-full max-w-md p-5"><h3 className="text-lg font-bold">Schedule publication</h3><div className="mt-5 grid grid-cols-2 gap-3"><Field label="Date"><input required type="date" value={date} onChange={e=>setDate(e.target.value)} className="input"/></Field><Field label="Time"><input required type="time" value={time} onChange={e=>setTime(e.target.value)} className="input"/></Field></div><div className="mt-5 flex justify-end gap-2"><button type="button" className="btn" onClick={()=>setSchedule(false)}>Cancel</button><button type="button" disabled={!date||!time} className="btn btn-primary" onClick={handleSubmit(d=>persist(d,"schedule"))}>Schedule</button></div></div></div>}
 </form>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="card p-5"><h3 className="section-title">{title}</h3><div className="mt-5">{children}</div></section>}function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block"><span className="label mb-1.5 block">{label}</span>{children}{error&&<span className="mt-1 block text-xs text-red-600">{error}</span>}</label>}
